use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'KMTIMSDK_Example' do
  
  pod 'KMAgoraRtc', :git => 'https://github.com/zhenlove/KMAgoraRtc.git'
  pod 'KMTIMSDK', :path => '../'

end
