use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'KMTIMSDK_Example' do
  pod 'KMTIMSDK', :path => '../'
  pod 'KMOnlineWeb',:path => '/Users/ed/github/KMOnlineWeb/'
#  pod 'KMTIM',:path => '/Users/ed/github/KMTIM/'
  pod 'CocoaAsyncSocket','7.6.3', :modular_headers => true, :configurations => ['Debug']
  pod 'Bagel','1.3.2', :configurations => ['Debug']
end
